### PR TITLE
Fixed pacc functionality for antiparallel CCs as well.

### PR DESCRIPTION
**Pull request by ajasja**
Also added/fixed unit tests.

### CODE REVIEW

**Comment by ajasja** [comment]
@ChrisWellsWood Hmm strange, any reason why the tests did not run on this pull request?

**Comment by ChrisWellsWood** [comment]
@ajasja It doesn't run the unit tests because the changes aren't actually in the ISAMBARD repo yet.

**Comment by ChrisWellsWood** [comment]
Breaking master isn't a big deal, we can always revert or people can clone from a specific commit. It is annoying that CircleCI doesn't run tests for pull requests, but I suppose it makes sense as people could just spam the service. Anyway, I ran the tests locally so it's no big deal. In future I could make a branch for PRs to be on the safe side.

**Comment by ajasja** [comment]
But I've seen tests on pull requests. *google* *google*, aha, that was [travisCI](https://docs.travis-ci.com/user/pull-requests/)  :)

**Comment by ChrisWellsWood** [comment]
Turns out I can turn it on but it has security implications so it's off by default: https://circleci.com/docs/1.0/fork-pr-builds/

I've turned it on for now as there are no secrets used in the build process.

**Pull request merged**
